[package]
name = "lithovm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
lithovm-bytecode = { path = "../bytecode" }
lithovm-receipts = { path = "../receipts" }
lithovm-zk-verifier = { path = "../zk-verifier" }
